version: "3.9"
services:
    mysql:
        image: mysql:8.0.12
        container_name: wp-mysql
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: testdaten
        networks:
            - web-prog
        ports:
            - target: 3306
              published: 3306
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wp-phpmyadmin
        networks:
            - web-prog
        environment:
            PMA_HOST: wp-mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - target: 80
              published: 8080
 networks:
  web-prog:


