version: "3.9"
services:
    mysql:
        image: mysql:8.0.12
        container_name: wp-mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: testdaten
        networks:
            - web-prog
        ports:
            - target: 3306
              published: 3306
        restart: always
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wp-phpmyadmin
        networks:
            - web-prog
        environment:
            PMA_HOST: wp-mysql
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_ROOT_PASSWORD: ""
        ports:
            - "8080:80"
        restart: always
networks:
    web-prog:


